server:
  port: 3344


#github 上配置文件地址
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1970989712/microservicecloud-config.git #github 配置文件地址