server:
  port: 8001

mybatis:
  type-aliases-package: com.zjl.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept #微服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/cloudDB02?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&useSSL=false
    username: xxxx 
    password: xxxx

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
